In [32]:
import pandas as pd
import numpy as np
data=pd.Series([1.2,-3.5,np.nan,0,None])
data

0    1.2
1   -3.5
2    NaN
3    0.0
4    NaN
dtype: float64

In [33]:
data.isna() # both np.nan,none value are taken as missing value

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [34]:
data.notna()

0     True
1     True
2    False
3     True
4    False
dtype: bool

In [35]:
data[data.notna()] #it returns the nonnull values and corresponding index values.

0    1.2
1   -3.5
3    0.0
dtype: float64

In [36]:
data.dropna()#it returns the Series with only the nonnull data and corresponding index values.

0    1.2
1   -3.5
3    0.0
dtype: float64

In [37]:
data=pd.DataFrame([[1.2,-3.5,np.nan,4],
                   [np.nan,0,7,None],
                   [4.7,7.4,-0.7,0.4]])
data

0    1    2    3
0  1.2 -3.5  NaN  4.0
1  NaN  0.0  7.0  NaN
2  4.7  7.4 -0.7  0.4

In [38]:
data.dropna(axis=1) #it will drop the nonnull value of column   

1
0 -3.5
1  0.0
2  7.4

In [39]:
data.dropna(axis=0)#it will drop the nonnull value of row   

0    1    2    3
2  4.7  7.4 -0.7  0.4

In [40]:
data.dropna(how='all')

0    1    2    3
0  1.2 -3.5  NaN  4.0
1  NaN  0.0  7.0  NaN
2  4.7  7.4 -0.7  0.4

In [41]:
data.dropna(how='any') #it will return the row where all value are nonnull.

0    1    2    3
2  4.7  7.4 -0.7  0.4

In [42]:
data.dropna(thresh=3)#it will drop the row where at least 3 are non-null value.

0    1    2    3
0  1.2 -3.5  NaN  4.0
2  4.7  7.4 -0.7  0.4

In [43]:
data.dropna(thresh=4)# at least 4 value are non-value are present and it checks rowwise.

0    1    2    3
2  4.7  7.4 -0.7  0.4

In [44]:
dic={0:99,1:999,2:9999} # it fill the null value according to the data given in dictionary
data.fillna(value=dic)

0    1       2    3
0   1.2 -3.5  9999.0  4.0
1  99.0  0.0     7.0  NaN
2   4.7  7.4    -0.7  0.4

# fillna

In [45]:
data.fillna(method='ffill')

C:\Users\E 555\AppData\Local\Temp\ipykernel_10932\1844443866.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')


0    1    2    3
0  1.2 -3.5  NaN  4.0
1  1.2  0.0  7.0  4.0
2  4.7  7.4 -0.7  0.4

In [46]:
data.fillna(0,limit=2) # it will fill the nan value with 0 in 0 and 1 index.

0    1    2    3
0  1.2 -3.5  0.0  4.0
1  0.0  0.0  7.0  0.0
2  4.7  7.4 -0.7  0.4

In [51]:
data.fillna(method='ffill',limit=1)# it specified,this is the maximum number of consecutive NaN value to ffill and bffill

C:\Users\E 555\AppData\Local\Temp\ipykernel_10932\2344523904.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill',limit=1)# it specified,this is the maximum number of consecutive NaN value to ffill and bffill


0    1    2    3
0  1.2 -3.5  NaN  4.0
1  1.2  0.0  7.0  4.0
2  4.7  7.4 -0.7  0.4

In [52]:
data.fillna(method='ffill',limit=2) # it checks column wise.

C:\Users\E 555\AppData\Local\Temp\ipykernel_10932\313917531.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill',limit=2)


0    1    2    3
0  1.2 -3.5  NaN  4.0
1  1.2  0.0  7.0  4.0
2  4.7  7.4 -0.7  0.4

In [48]:
data.fillna(method='bfill',limit=2) # it will check the o and 1 row

C:\Users\E 555\AppData\Local\Temp\ipykernel_10932\617972290.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill',limit=2) # it will check the o and 1 row


0    1    2    3
0  1.2 -3.5  7.0  4.0
1  4.7  0.0  7.0  0.4
2  4.7  7.4 -0.7  0.4

# Data transformation

In [64]:
data1=pd.DataFrame({"c1":['a','b','a','b','a','b'],'c2':[1,1,1,2,2,2]})
data1

c1  c2
0  a   1
1  b   1
2  a   1
3  b   2
4  a   2
5  b   2

In [65]:
data1.duplicated() # it will return boolean series true or false if row wise data repeted or not

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [66]:
data1.drop_duplicates()#it will return the dataframe with rows where the duplicated array is false.it removes the repeted value.

c1  c2
0  a   1
1  b   1
3  b   2
4  a   2

In [67]:
data1.fillna(method='ffill',limit=1)# it specified,this is the maximum number of consecutive NaN value to ffill and bffill

C:\Users\E 555\AppData\Local\Temp\ipykernel_10932\3361061223.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1.fillna(method='ffill',limit=1)# it specified,this is the maximum number of consecutive NaN value to ffill and bffill


c1  c2
0  a   1
1  b   1
2  a   1
3  b   2
4  a   2
5  b   2

In [68]:
data1['c3']=['!','@','#','$','#','@']
data1.drop_duplicates('c3')

c1  c2 c3
0  a   1  !
1  b   1  @
2  a   1  #
3  b   2  $

In [69]:
data1.drop_duplicates(subset=['c3'],keep='first')# it drop the first occurences of duplicates

c1  c2 c3
0  a   1  !
1  b   1  @
2  a   1  #
3  b   2  $

In [70]:
data1.drop_duplicates(subset=['c3'],keep='last')# it drop the last occurences of duplicates

c1  c2 c3
0  a   1  !
3  b   2  $
4  a   2  #
5  b   2  @

In [71]:
import pandas as pd 
import numpy as np
frame=pd.DataFrame(np.random.randn(4,3),columns=list('abc'),index=['w','x','y','z'])
frame

a         b         c
w  0.920705  1.453950 -1.101107
x  0.601765  0.571386 -0.895126
y -0.811973  0.561183  1.344552
z -1.147386 -0.171267  0.032527

In [72]:
col=lambda x:x.max()
frame.apply(col)

a    0.920705
b    1.453950
c    1.344552
dtype: float64

In [75]:
index=lambda x:x.max()
frame.apply(index)

a    0.920705
b    1.453950
c    1.344552
dtype: float64

In [76]:
ele=lambda x:x**2
frame.applymap(ele)# it will works element wise on a dataframe

C:\Users\E 555\AppData\Local\Temp\ipykernel_10932\1566100443.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(ele)


a         b         c
w  0.847698  2.113970  1.212437
x  0.362121  0.326482  0.801250
y  0.659300  0.314926  1.807821
z  1.316495  0.029333  0.001058

In [77]:
frame['a'].map(ele)# it will return the columne 1st element wise

w    0.847698
x    0.362121
y    0.659300
z    1.316495
Name: a, dtype: float64

In [78]:
frame1=pd.DataFrame({'Name':['salman','aiswaraya','shahid','kareena'],'Height':[1.68,1.63,1.71,1.65],'Weight':[78,55,72,53]})
frame1

Name  Height  Weight
0     salman    1.68      78
1  aiswaraya    1.63      55
2     shahid    1.71      72
3    kareena    1.65      53

In [83]:
maximum_height=frame1.loc[frame1['Height'].idxmax(),['Name']]
maximum_height

Name    shahid
Name: 2, dtype: object

In [85]:
ele= lambda x:x**2
x=frame1['Height'].map(ele)
y=frame1['Weight']
frame1['BMI']=y/x
frame1

Name  Height  Weight        BMI
0     salman    1.68      78  27.636054
1  aiswaraya    1.63      55  20.700817
2     shahid    1.71      72  24.622961
3    kareena    1.65      53  19.467401

In [86]:
ow=lambda x:'Obessed' if x>20 else'Normal'
frame1['Category']=frame1['BMI'].map(ow)
frame1

Name  Height  Weight        BMI Category
0     salman    1.68      78  27.636054  Obessed
1  aiswaraya    1.63      55  20.700817  Obessed
2     shahid    1.71      72  24.622961  Obessed
3    kareena    1.65      53  19.467401   Normal

In [94]:
Name_Gen={'salman':'Male','aiswaraya':'Female','shahid':'Male','kareena':'Female'}
frame1["Gender"]=frame1['Name'].map(Name_Gen)
frame1

Name  Height  Weight        BMI Category  Gender
0     salman    1.68      78  27.636054  Obessed    Male
1  aiswaraya    1.63      55  20.700817  Obessed  Female
2     shahid    1.71      72  24.622961  Obessed    Male
3    kareena    1.65      53  19.467401   Normal  Female

In [95]:
data1.replace(to_replace="a",value='*') #single value replacement

c1  c2 c3
0  *   1  !
1  b   1  @
2  *   1  #
3  b   2  $
4  *   2  #
5  b   2  @

In [96]:
data1.replace(to_replace=["a","b"],value='*') # multiple value replacement

c1  c2 c3
0  *   1  !
1  *   1  @
2  *   1  #
3  *   2  $
4  *   2  #
5  *   2  @

In [97]:
data1.replace({'a':'*','b':'&'}) # 

c1  c2 c3
0  *   1  !
1  &   1  @
2  *   1  #
3  &   2  $
4  *   2  #
5  &   2  @

In [98]:
data1.replace(to_replace=["a","b"],value=['*','&']) # replace in form of list 

c1  c2 c3
0  *   1  !
1  &   1  @
2  *   1  #
3  &   2  $
4  *   2  #
5  &   2  @

In [99]:
data1.replace(to_replace={'c1':{'a':'*','b':'&'}})# replace in form of dictionary of dictionary


c1  c2 c3
0  *   1  !
1  &   1  @
2  *   1  #
3  &   2  $
4  *   2  #
5  &   2  @

In [102]:
data1=pd.DataFrame({"c1":['a','b','a','b','a','b','a'],'c2':['a',1,1,1,2,2,2]},index=['d','s','f','g','h','j','k'])
data1

c1 c2
d  a  a
s  b  1
f  a  1
g  b  1
h  a  2
j  b  2
k  a  2

In [103]:
def transform(x):
    return x.upper()
data1.index.map(transform)

Index(['D', 'S', 'F', 'G', 'H', 'J', 'K'], dtype='object')

In [105]:
data1.index=data1.index.map(transform)
data1

c1 c2
D  a  a
S  b  1
F  a  1
G  b  1
H  a  2
J  b  2
K  a  2

In [106]:
data1.rename(index=str.title,columns=str.upper)

C1 C2
D  a  a
S  b  1
F  a  1
G  b  1
H  a  2
J  b  2
K  a  2

In [108]:
data1.rename(str.lower,axis='columns')

c1 c2
D  a  a
S  b  1
F  a  1
G  b  1
H  a  2
J  b  2
K  a  2

In [109]:
data1.rename(str.lower,axis='index')

c1 c2
d  a  a
s  b  1
f  a  1
g  b  1
h  a  2
j  b  2
k  a  2

# Discretization

In [6]:
import numpy as np
x=np.array([1,2,3,7,4])
pd.cut(x,bins=2) # it will do by default bin sizing according to the element

[(0.994, 4.0], (0.994, 4.0], (0.994, 4.0], (4.0, 7.0], (0.994, 4.0]]
Categories (2, interval[float64, right]): [(0.994, 4.0] < (4.0, 7.0]]

In [111]:
x=np.array([1,2,3,7,4])
y=[0,2,6] 
pd.cut(x,bins=y)

[(0.0, 2.0], (0.0, 2.0], (2.0, 6.0], NaN, (2.0, 6.0]]
Categories (2, interval[int64, right]): [(0, 2] < (2, 6]]

In [7]:
import pandas as pd
bins=pd.IntervalIndex.from_tuples([(0,2),(2,3),(3,7)])
x=np.array([1,2,3,7,4])
pd.cut(x,bins)

[(0, 2], (0, 2], (2, 3], (3, 7], (3, 7]]
Categories (3, interval[int64, right]): [(0, 2] < (2, 3] < (3, 7]]

In [13]:
x=np.array([1,2,3,7,4])
y=[0,4,5,7]
A=pd.cut(x,bins=y)
A.codes


array([0, 0, 0, 2, 0], dtype=int8)

In [16]:
A.categories # it will return the interval.

IntervalIndex([(0, 4], (4, 5], (5, 7]], dtype='interval[int64, right]')

In [17]:
A.categories[0]

Interval(0, 4, closed='right')

In [18]:
x=np.array([1,2,3,7,4])
y=[0,2,6] 
pd.cut(x,bins=y,right=False) # it will reverse the exclusive to inclusive.by default it takes right as true

[[0.0, 2.0), [2.0, 6.0), [2.0, 6.0), NaN, [2.0, 6.0)]
Categories (2, interval[int64, left]): [[0, 2) < [2, 6)]

In [19]:
data=np.random.uniform(size=20)
pd.cut(data,4,precision=2)# it used to represent round up the big decimal places to samll decimal places 

[(0.15, 0.33], (0.68, 0.85], (0.68, 0.85], (0.68, 0.85], (0.33, 0.5], ..., (0.68, 0.85], (0.33, 0.5], (0.33, 0.5], (0.15, 0.33], (0.33, 0.5]]
Length: 20
Categories (4, interval[float64, right]): [(0.15, 0.33] < (0.33, 0.5] < (0.5, 0.68] < (0.68, 0.85]]

In [20]:
ls=["bad","medium","good","Best"]
pd.cut(data,4,precision=2,labels=ls)

['bad', 'Best', 'Best', 'Best', 'medium', ..., 'Best', 'medium', 'medium', 'bad', 'medium']
Length: 20
Categories (4, object): ['bad' < 'medium' < 'good' < 'Best']

In [33]:
data=np.random.seed(42)
data=np.random.uniform(size=20)
pd.cut(data,4,precision=2)

[(0.26, 0.5], (0.73, 0.97], (0.5, 0.73], (0.5, 0.73], (0.02, 0.26], ..., (0.02, 0.26], (0.26, 0.5], (0.5, 0.73], (0.26, 0.5], (0.26, 0.5]]
Length: 20
Categories (4, interval[float64, right]): [(0.02, 0.26] < (0.26, 0.5] < (0.5, 0.73] < (0.73, 0.97]]

In [34]:
data=np.random.seed(42)
data=np.random.uniform(size=20)
pd.cut(data,4,precision=3)

[(0.258, 0.495], (0.733, 0.97], (0.495, 0.733], (0.495, 0.733], (0.0196, 0.258], ..., (0.0196, 0.258], (0.258, 0.495], (0.495, 0.733], (0.258, 0.495], (0.258, 0.495]]
Length: 20
Categories (4, interval[float64, right]): [(0.0196, 0.258] < (0.258, 0.495] < (0.495, 0.733] < (0.733, 0.97]]

In [35]:
data=np.random.seed(42)
data=np.random.uniform(size=20)
pd.cut(data,4,precision=1)

[(0.3, 0.5], (0.7, 1.0], (0.5, 0.7], (0.5, 0.7], (0.02, 0.3], ..., (0.02, 0.3], (0.3, 0.5], (0.5, 0.7], (0.3, 0.5], (0.3, 0.5]]
Length: 20
Categories (4, interval[float64, right]): [(0.02, 0.3] < (0.3, 0.5] < (0.5, 0.7] < (0.7, 1.0]]

In [36]:
data=np.random.standard_normal(1000)
quartiles=pd.qcut(data,4,precision=2) # it distribute the intervalas such a manner that each interval has eual numbers.
quartiles

[(-3.25, -0.65], (0.04, 0.66], (-3.25, -0.65], (-3.25, -0.65], (0.66, 3.85], ..., (0.04, 0.66], (0.66, 3.85], (-3.25, -0.65], (0.66, 3.85], (0.04, 0.66]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.25, -0.65] < (-0.65, 0.04] < (0.04, 0.66] < (0.66, 3.85]]

In [37]:
pd.value_counts(quartiles)

C:\Users\E 555\AppData\Local\Temp\ipykernel_8856\3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-3.25, -0.65]    250
(-0.65, 0.04]     250
(0.04, 0.66]      250
(0.66, 3.85]      250
Name: count, dtype: int64

In [41]:
data1=np.random.standard_normal(1000)
quart=pd.cut(data1,4,precision=2)
quart

[(-1.28, 0.45], (-3.03, -1.28], (0.45, 2.19], (-1.28, 0.45], (-1.28, 0.45], ..., (0.45, 2.19], (-3.03, -1.28], (-3.03, -1.28], (-1.28, 0.45], (0.45, 2.19]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.03, -1.28] < (-1.28, 0.45] < (0.45, 2.19] < (2.19, 3.93]]

In [42]:
pd.value_counts(quart)

C:\Users\E 555\AppData\Local\Temp\ipykernel_8856\4033729106.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quart)


(-1.28, 0.45]     566
(0.45, 2.19]      327
(-3.03, -1.28]     95
(2.19, 3.93]       12
Name: count, dtype: int64

In [49]:
x=pd.DataFrame(np.random.standard_normal((1000,4)))
x

0         1         2         3
0   -0.174444 -0.747429 -1.331913  1.307964
1    0.554639 -1.623918  0.763142  0.922481
2    0.124376  1.598111  0.216720 -1.416824
3    0.365169  0.244897 -0.603297  0.573559
4   -1.667665  0.990567 -0.878122 -0.984946
..        ...       ...       ...       ...
995  1.237151  1.312208 -0.884109 -0.153785
996 -0.143423 -0.032656  0.064295  0.946861
997 -0.747217 -0.846347  1.236620 -0.462645
998 -1.263035 -0.485130 -0.330053  1.554963
999  0.924826  1.147521  0.819974  0.946244

[1000 rows x 4 columns]

In [53]:
A=x.describe()
A

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.064508     0.043310     0.012710    -0.025365
std       1.038320     1.008491     1.009117     0.966308
min      -3.375579    -3.329504    -3.321115    -3.033989
25%      -0.645304    -0.652419    -0.664803    -0.627620
50%       0.069814     0.002883     0.013479     0.009662
75%       0.746545     0.742442     0.667983     0.614626
max       3.287761     3.428910     3.377768     2.824167

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
        6, 6, 7, 7, 7, 7], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
        2, 3, 0, 1, 2, 3], dtype=int64))

In [57]:
x[(x.abs()>3).any(axis="columns")]

0         1         2         3
41  -3.375579 -0.449650  0.763903 -0.390394
80   0.229573 -0.724364  3.377768  0.515720
102 -1.153483 -0.370037 -3.321115 -0.590222
112  3.287761 -0.141150 -0.325739  0.113334
182  0.873066  0.608984  0.418912 -3.033989
423  3.284118  0.783304 -0.267004  0.869031
538 -0.584229  3.040687 -0.968013  1.147803
547  0.747059 -1.321209  3.096589  0.028566
552  1.044386  3.428910  0.115152 -1.311737
607  3.186575  1.344434  0.701131 -0.912804
631 -3.082562  0.401430 -0.643872  1.111145
732 -0.866571  0.349012  3.285724  0.695166
891 -0.064398 -3.329504  0.247333 -0.300814
909 -2.398163 -1.408431 -3.250333  2.112089
974  3.140423 -0.149585  1.038728 -1.238161

In [58]:
np.sign(x)

0    1    2    3
0   -1.0 -1.0 -1.0  1.0
1    1.0 -1.0  1.0  1.0
2    1.0  1.0  1.0 -1.0
3    1.0  1.0 -1.0  1.0
4   -1.0  1.0 -1.0 -1.0
..   ...  ...  ...  ...
995  1.0  1.0 -1.0 -1.0
996 -1.0 -1.0  1.0  1.0
997 -1.0 -1.0  1.0 -1.0
998 -1.0 -1.0 -1.0  1.0
999  1.0  1.0  1.0  1.0

[1000 rows x 4 columns]

In [70]:
data={"A":[10,30,50,70],"B":[20,40,60,80]}
df=pd.DataFrame(data)
df

A   B
0  10  20
1  30  40
2  50  60
3  70  80

In [73]:
df.take([0,2])

A   B
0  10  20
2  50  60

In [76]:
df1=pd.DataFrame(np.arange(5*7).reshape((5,7)))
df1

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [77]:
sampler=np.random.permutation(5)
sampler

array([0, 2, 3, 1, 4])

In [80]:
column_sampler=np.random.permutation(7)
column_sampler
df1.take(column_sampler,axis="columns")# it will select a permutation of the columns

6   2   1   4   3   5   0
0   6   2   1   4   3   5   0
1  13   9   8  11  10  12   7
2  20  16  15  18  17  19  14
3  27  23  22  25  24  26  21
4  34  30  29  32  31  33  28

In [81]:
df1.sample(n=3)# to select a random subset without replacement(the same roe cannot aapper twice)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6

In [83]:
df1.sample(n=3,replace=True)# for replacement we can pass the replace to sample

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13